---
title: "analysis"
author: "tlaguna"
---

Load packages

```{r}
#| output: false
library(babynames)
library(knitr)
library(dplyr)
library(ggplot2)
```

Visualize first 10 names

```{r}
head(babynames, n=10) |> kable()
```

Functions

```{r}
# function to get the most frequent baby names over a time period
get_most_frequent <- function(babynames, select_sex, from = 1950) {
  most_freq <- babynames |>
    filter(sex == select_sex, year > from) |>
    group_by(name) |>
    summarise(average = mean(prop)) |>
    arrange(desc(average))
  return(most_freq)
}

# plot the top most popular names
plot_top <- function(x, babynames, select_sex, top = 10, from = 1950) {
  topx <- x$name[1:top]
  
  p <- babynames |>
    filter(name %in% topx, sex == select_sex, year > from) |>
    ggplot(aes(x = year, y = prop, color = name)) +
    geom_line() +
    scale_color_brewer(palette = "Paired") +
    theme_classic()
  
  return(p)
}
```

Plot top girl names:

```{r}
#| label: fig-line-girls
#| fig-cap: "Line plot displaying proportion of top 10 girl names by year"
get_most_frequent(babynames, select_sex = "F") |>
  plot_top(babynames, select_sex = "F", top = 10)
```

In @fig-line-girls you can see that there has been a peak in popularity for 'Lisa', 'Jennifer' and 'Jessica'.

Plot top boys names:

```{r}
#| label: fig-line-boys
#| fig-cap: "Line plot displaying proportion of top 10 boy names by year"
get_most_frequent(babynames, select_sex = "M") |>
  plot_top(babynames, select_sex = "M", top = 10)
```

@fig-line-boys shows that names that were popular before 1990 are relatively infrequent after 2000.
